# name: Flutter CI
# on:
#   push:
#     branches:
#       - master
# jobs:
#  build_apk:
#    name: Build Flutter (Android)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with: 
#         java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#        env:
#          KEY_JKS: ${{ secrets.RELEASE_KEYSTORE_FILE }}
#          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#      - name: Decode Keystore
#        run: |
#          echo "${{secrets.RELEASE_KEYSTORE_FILE}}" > keyfile
#          base64 -d keyfile > android/key.jks
#      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.env }} event."
#      - name: Create key.properties
#        run: |
#         touch android/key.properties
#         echo "storePassword=$SIGNING_STORE_PASSWORD
#         keyPassword=$SIGNING_KEY_PASSWORD
#         keyAlias=$SIGNING_KEY_ALIAS
#         storeFile=../key.jks"  > ./android/key.properties
#      - name: Create key.properties
#        run: |
#         cat ./android/key.properties
#      - name: Get dependencies
#        run: flutter pub get
#      - name: Build APK
#        run: flutter build apk
#      - uses: actions/upload-artifact@v1      
#        with:        
#          name: release-apk        
#          path: build/app/outputs/apk/release/app-release.apk